name: Build deployment images

on:
  push:
    branches:
      - main
    paths:
     - deployment/**

jobs:
  push:
    name: "deployment/${{ matrix.deployment  }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deployment:
          - minimal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./deployment/${{ matrix.deployment }}
          platforms: linux/amd64
          file: ./deployment/${{ matrix.deployment }}/Dockerfile
          push: true
          tags: ghcr.io/zenwaypl/deployment:${{ matrix.deployment }}